### ISSUE TITLE
k8s-prometheus-adapter authentication with AWS eks.2

### ISSUE THREAD

**Issue by twittyc** [DirectXMan12/k8s-prometheus-adapter#122]
Hey guys,

Is there any documentation on how to authenticate with EKS apiserver? 
I was under the impression I'm suppose to use --requestheader-client-ca-file with the ca.crt file generated for the worker nodes. However, this isn't working.

```
1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (209.558µs) 401 [[kubectl/v1.10.3 (darwin/amd64) kubernetes/2bba012] 10.99.3.99:51048]
E1026 14:45:37.424947       1 authentication.go:62] Unable to authenticate the request due to an error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

Thanks!

**Comment by twittyc** [comment]
Bump on this instead of opening a new issue. I opened a ticket with AWS support which went all the way up to the service team for EKS. They were also not able to get prometheus adapter to work with EKS. 

> I am able to reproduce similar error message with custom prometheus adapter. 
>Upon debugging further, EKS core API server doesn't use certificate based authentication for it's clients i.e. client-ca-file flag isn't set in core API server then the extension API server fails to start with error message
>Error: cluster doesn't provide client-ca-file
>In order to fix this issue, prometheus adapter should patch their custom metric API server which should be able to start and not require that both client-ca and requestheader-ca be present in the extension-apiserver-authentication ConfigMap. This allows EKS clusters which don't use certificate based authentication for core API server to be able to dynamically discover the requestheader-ca instead of having to mount it as a secret.

**Comment by nishanth-pinnapareddy** [comment]
How did you generate `cm-adapter-serving-certs`?

**Comment by nishanth-pinnapareddy** [comment]
How did you generate `cm-adapter-serving-certs`?  Did you use `CertificateSigningRequest`?

**Comment by DirectXMan12** [comment]
I think we need to do a dependency update to pull in the latest dependencies that have the EKS fix.  @brancz FYI

**Comment by DirectXMan12** [comment]
Whoops, sorry, responded too fast :-).  Let me actually read through this one

**Comment by metalmatze** [comment]
Would it be helpful to have self signed certs when starting out?

**Comment by DirectXMan12** [comment]
So, for the "cluster doesn't provide client-ca file" we just need the updated API machinery deps that fix that issue with EKS.  It's just a matter of pulling in the most recent release of the API machinery, and making sure it didn't break anything.

**Comment by karanmagdani** [comment]
@twittyc Did you figure out a way around this? I am currently blocked with the same issue. I have created a ticket with AWS as well

**Comment by twittyc** [comment]
I haven't been able to work on this. My priorities have shifted. Looks like you would need to update the API machinery deps in the Gopkg.toml and rebuild as this was fixed in the upstream dependency and the app needs to be rebuilt with those changes.

**Comment by q3aiml** [comment]
This has been working for me on EKS since #110. Is everyone else still seeing this with v0.3.0+?

**Comment by okrasnyiblues** [comment]
@q3aiml are you installing it via helm or using anything else ? Because i installed it using helm and still have this issue.

**Comment by okrasnyiblues** [comment]
like i already said i use v0.4.0, but still get error with certificates

**Comment by q3aiml** [comment]
Sorry, I missed that edit. Email only has the original comment without the version edit so I should pay more attention to the web interface. Sorry for the trouble...

**Comment by okrasnyiblues** [comment]
I have just deleted cache of helm and tried installing adapter again and it worked. So I'm pretty sure it works on eks now.

**Comment by twittyc** [comment]
This works -- closing issue. Thanks guys!

**Comment by calebwoofenden** [comment]
I am seeing this error message logged repeatedly on the prometheus-adapter pod, but it seems to be working. I am able to access the metrics I wanted to be exposed through custom.metrics.k8s.io. Is this something I should try to fix, or is there a way to ignore this error message? It's filling my logs.
